jobdata/jobdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('crawler.urls', namespace='crawler')),
]

jobdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('jobdetails.urls', namespace='jobdetails')),
    url('', include('crawler_api.urls', namespace='crawler_api')),
]

jobdetails/urls.py
from django.conf.urls import url
from jobdetails.views import job_details_agents, job_details_dates, job_details_files, job_details_view_html, job_details_view_json, job_details_view_data

urlpatterns = [
    url(r'^$', job_details_agents, name='job_details_agents'),
    url(r'^(?P<crawler>[0-9]+)/dates/$', job_details_dates, name='job_details_dates'),
    url(r'^(?P<crawler>[0-9]+)/date/(?P<date>[-\w]+)/files/$', job_details_files, name='job_details_files'),
    url(r'^(?P<crawler>[0-9]+)/date/(?P<date>[-\w]+)/(?P<file>.*)/view_html/$', job_details_view_html, name='job_details_view_html'),
    url(r'^(?P<crawler>[0-9]+)/date/(?P<date>[-\w]+)/(?P<file>.*)/view_json/$', job_details_view_json, name='job_details_view_json'),
    url(r'^(?P<crawler>[0-9]+)/date/(?P<date>[-\w]+)/(?P<job>.*)/view_data/$', job_details_view_data, name='job_details_view_data'),

]

jobdetails/models.py
from __future__ import unicode_literals

from django.db import models


class CrawlerAgent(models.Model):
    tld = models.CharField(max_length=100)
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.tld

    def __unicode__(self):
        return u"%s" % self.id


class JobInfo(models.Model):
    crawler_agent = models.ForeignKey(CrawlerAgent)
    job_page_url = models.CharField(max_length=500)
    job_title = models.CharField(max_length=200)
    path_gcs = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return u"%s" % self.crawler_agent_id


class JobData(models.Model):
    job = models.ForeignKey(JobInfo)
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    nature = models.CharField(max_length=100)
    desc = models.CharField(max_length=20000)

    def __str__(self):
        return u"%s" % self.title

jobdetails/views.py
from django.http import HttpResponse
from django.shortcuts import render
from datetime import datetime
import base64
import json
from collections import OrderedDict

from .models import CrawlerAgent, JobInfo, JobData
from gcloud_storage import GcloudStorage


def job_details_agents(request):
    if request.method == 'GET':
        crawler_agents = CrawlerAgent.objects.all()
        for crawler in crawler_agents:
            crawler.votes = JobInfo.objects.filter(crawler_agent_id=crawler.id, status=True).count()
        return render(request, 'jobdetails/agents.html', {'crawlers': crawler_agents, })
    else:
        return HttpResponse("<p>There is no posting here :)</p>")


def job_details_dates(request, crawler):
    if request.method == 'GET':
        crawler_id = crawler
        crawler = CrawlerAgent.objects.get(id=int(crawler_id.encode('utf-8')))
        jobs = JobInfo.objects.filter(crawler_agent_id=int(crawler.id), status=True).order_by('-created_at')
        dates_dict = {}
        for job in jobs:
            if str(job.created_at.date()) in dates_dict:
                dates_dict[str(job.created_at.date())] = int(dates_dict[str(job.created_at.date())]) + 1
            else:
                dates_dict[str(job.created_at.date())] = 1
            ordered_dates_dict = OrderedDict(sorted(dates_dict.items()))
        title_list = []
        location_list = []
        nature_list = []
        desc_list = []
        jobs = JobData.objects.all()
        for date_key in ordered_dates_dict.keys():
            title_length = 0
            location_length = 0
            nature_length = 0
            desc_length = 0
            title_count = 0
            location_count = 0
            nature_count = 0
            desc_count = 0
            for job in jobs:
                if str(job.job.created_at.date()) == str(date_key):
                    title_length += len(str(job.title))
                    title_count += 1
            title_list.append(title_length/title_count)
            for job in jobs:
                if str(job.job.created_at.date()) == str(date_key):
                    location_length += len(str(job.location))
                    location_count += 1
            location_list.append(location_length/location_count)
            for job in jobs:
                if str(job.job.created_at.date()) == str(date_key):
                    nature_length += len(str(job.nature))
                    nature_count += 1
            nature_list.append(nature_length/nature_count)
            for job in jobs:
                if str(job.job.created_at.date()) == str(date_key):
                    desc_length += len(str(job.desc))
                    desc_count += 1
            desc_list.append(desc_length/desc_count)

    return render(request, 'jobdetails/dates.html', {'title_list': title_list, 'location_list': location_list, 'nature_list': nature_list, 'desc_list': desc_list, 'counts': ordered_dates_dict, 'crawler_id': crawler})


def job_details_files(request, crawler, date):
    if request.method == 'GET':
        crawler_id = crawler
        crawler = CrawlerAgent.objects.get(id=int(crawler_id.encode('utf-8')))
        date = date
        date_field = datetime.strptime(str(date), '%Y-%m-%d')
        files = JobInfo.objects.filter(crawler_agent_id=int(crawler.id), status=True, created_at__startswith=str(date_field.date())).order_by('-created_at')

        return render(request, 'jobdetails/files_table.html', {'files': files, 'date': date, 'crawler_id_date': crawler})


def job_details_view_json(request, crawler, date, file):
    if request.method == 'GET':
        crawler_id = crawler
        crawler = CrawlerAgent.objects.get(id=int(crawler_id.encode('utf-8')))
        date = date
        file = file
        gcs = GcloudStorage()
        bucket = gcs.get_bucket('job-data-development')
        blob = bucket.get_blob(str(file))
        blob_string = blob.download_as_string()

        return render(request, 'jobdetails/view_json.html', {'title': file, 'blob_string': blob_string, 'date': date, 'crawler_id_date_file': crawler})


def job_details_view_html(request, crawler, date, file):
    if request.method == 'GET':
        crawler_id = crawler
        crawler = CrawlerAgent.objects.get(id=int(crawler_id.encode('utf-8')))
        date = date
        file = file
        gcs = GcloudStorage()
        bucket = gcs.get_bucket('job-data-development')
        blob = bucket.get_blob(str(file))
        blob_string = blob.download_as_string()
        blob_json = json.loads(str(blob_string))
        html_b64 = str(blob_json['job_html_b64'])
        html = base64.b64decode(html_b64)
        title = str(blob_json['job_title'])

        return render(request, 'jobdetails/view_html.html', {'html': html, 'title': title, 'date': date, 'crawler_id_date_file': crawler})


def job_details_view_data(request, crawler, date, job):
    if request.method == 'GET':
        crawler_id = crawler
        crawler = CrawlerAgent.objects.get(id=int(crawler_id.encode('utf-8')))
        date = date
        job_data = JobData.objects.get(job_id=int(job))
        title = job_data.title
        return render(request, 'jobdetails/view_data.html', {'title': title, 'job_data': job_data, 'date': date, 'crawler_id_date_file': crawler})

jobdetails/templates/jobdetails/agents.html
{% extends 'jobdetails/base.html' %}
{% block content %}
<script>
window.onload = function() {
var canvas = document.getElementById('myChart');
canvas.width  = 400;
canvas.height = 400;

var ctx = document.getElementById("myChart");
var data = {
  labels: [{% for crawler in crawlers%}
            "{{crawler.tld}}",
            {% endfor %}
  ],
    datasets: [
        {
            label: "Jobs Per Agent",
            backgroundColor: "rgba(255,99,132,0.2)",
            borderColor: "rgba(255,99,132,1)",
            borderWidth: 1,
            hoverBackgroundColor: "rgba(255,99,132,0.4)",
            hoverBorderColor: "rgba(255,99,132,1)",
            data: [{% for crawler in crawlers%}
                    {{crawler.votes}},
                    {% endfor %}
            ],
        }
    ]
};
var myBarChart = new Chart(ctx, {
    type: "bar",
    data: data,
    options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
                xAxes: [{
                        stacked: true
                }],
                yAxes: [{
                        stacked: true
                }]
            }
        }
});
}
</script>
<div class="col-lg-12 nopadding" style="margin-bottom:20px;">
  <canvas id="myChart" class="chardiv"></canvas>
</div>
      {% for crawler in crawlers %}
<div class="col-lg-3 center-block text-center">
  <a href="{% url 'jobdetails:job_details_dates' crawler=crawler.id %}" class="custom"> <span class="center-block text-center fa fa-folder fa-3x bluetext"></span></a><br/>
  <h4 class="text-center blacktext"><a href="{% url 'jobdetails:job_details_dates' crawler=crawler.id %}" class="custom">{{crawler.tld}}</a></h4>
  </div>
  {% endfor %}

{% endblock content %}

jobdetails/templates/jobdetails/base.html
{% load staticfiles %}
<html>
<head>
  <title>Jobdata Details</title>
  <link rel="stylesheet" type="text/css" href="{% static 'jobdetails/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'jobdetails/style.css' %}" type="text/css">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <script src="{% static 'jobdetails/jquery.min.js' %}"></script>
  <script src="{% static 'jobdetails/bootstrap.min.js' %}"></script>
  <script src="{% static 'jobdetails/Chart.js'%}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container-fluid">
    <div class="row nopadding">
    <div class="col-lg-12 nopadding">
      <div class="bluebg col-lg-12 nopadding" style="margin-bottom:20px;">
      <h3 class="text-center whitetext">Job Details</h3>
      </div>
      <div class="col-lg-12 nopadding center-block text-left" style="margin-bottom:20px;">
<ol class="breadcrumb" style="margin-bottom: 5px;">
  <li><a href="{% url 'jobdetails:job_details_agents' %}">Home</a></li>
  {% if crawler_id %}
  <li class="active">{{crawler_id.tld}}</li>
  {% endif %}
  {% if crawler_id_date %}
  <li><a href="{% url 'jobdetails:job_details_dates' crawler=crawler_id_date.id %}">{{crawler_id_date.tld}}</a></li>
  <li class="active">{{date}}</li>
  {% endif %}
  {% if crawler_id_date_file %}
  <li><a href="{% url 'jobdetails:job_details_dates' crawler=crawler_id_date_file.id %}">{{crawler_id_date_file.tld}}</a></li>
  <li><a href="{% url 'jobdetails:job_details_files' crawler=crawler_id_date_file.id date=date %}">{{date}}</a></li>
  <li class="active">{{title}}</li>
  {% endif %}
</ol>
      </div>
      <div class="col-lg-12 nopadding">
      {%block content %}

      {% endblock content %}
      </div>
          </div>
    </div>
  </div>
</body>
</html>

jobdetails/templates/jobdetails/dates.html
{% extends 'jobdetails/base.html' %}
{% block content %}
<script>
window.onload = function() {
var canvas = document.getElementById('myChart');
canvas.width  = 400;
canvas.height = 400;

var ctx = document.getElementById("myChart");
var data = {
  labels: [ {% for count, value in counts.items %}
            "{{count}}",
            {% endfor %}
    ],
    datasets: [
        {
            label: "Jobs Per Date",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "rgba(75,192,192,0.4)",
            borderColor: "rgba(75,192,192,1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(75,192,192,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(75,192,192,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: [ {% for count, value in counts.items %}
            {{value}},
            {% endfor %}
            ],
        }
    ]
};
var myBarChart = new Chart(ctx, {
    type: "line",
    data: data,
    options: {
        responsive: true,
        maintainAspectRatio: false,

        }
});

var canvas2 = document.getElementById('myChart2');
canvas2.width  = 400;
canvas2.height = 400;

var ctx2 = document.getElementById("myChart2");
var data = {
  labels: [ {% for count, value in counts.items %}
            "{{count}}",
            {% endfor %}
    ],
    datasets: [
        {
            label: "Average Title Length",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "rgba(153, 51, 255,0.4)",
            borderColor: "rgba(153, 51, 255,1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(153, 51, 255,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(153, 51, 255,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: [ {% for title in title_list %}
            {{title}},
            {% endfor %}
            ],
        },
        {
            label: "Average Location Length",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "rgba(0, 102, 255,0.4)",
            borderColor: "rgba(0, 102, 255,1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(0, 102, 255,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(0, 102, 255,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data:[ {% for location in location_list %}
            {{location}},
            {% endfor %}
],
        },
        {
            label: "Average Nature Length",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "rgba(255, 102, 0,0.4)",
            borderColor: "rgba(255, 102, 0,1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(255, 102, 0,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(255, 102, 0,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: [ {% for nature in nature_list %}
            {{nature}},
            {% endfor %}
            ],
        },
        {
            label: "Average Desc Length",
            fill: false,
            lineTension: 0.1,
            backgroundColor: "rgba(51, 204, 51,0.4)",
            borderColor: "rgba(51, 204, 51,1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(51, 204, 51,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(51, 204, 51,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: [ {% for desc in desc_list %}
            {{desc}},
            {% endfor %}
            ],
        },


    ]
};
var myBarChart2 = new Chart(ctx2, {
    type: "line",
    data: data,
    options: {
        responsive: true,
        maintainAspectRatio: false,

        }
});
}
</script>
<div class="col-lg-12 nopadding" style="margin-bottom:20px;">
  <canvas id="myChart" class="chardiv"></canvas>
</div>
<div class="col-lg-12 nopadding" style="margin-bottom:20px;">
  <canvas id="myChart2" class="chardiv"></canvas>
</div>
{% for date in counts %}
<div class="col-lg-3 center-block text-center">
  <a href="{% url 'jobdetails:job_details_files' crawler=crawler_id.id date=date %}" class="custom">
    <span class="center-block text-center fa fa-folder fa-3x bluetext"></span> </a><br/>
  <h4 class="text-center blacktext"><a href="{% url 'jobdetails:job_details_files' crawler=crawler_id.id date=date %}" class="custom">{{date}}</a></h4>
  </div>
  {% endfor %}
  {% endblock content %}

jobdetails/templates/jobdetails/files.html
{% extends 'jobdetails/base.html' %}
{% block content %}
{% for file in files %}
<div class="boxlg col-lg-4 center-block text-center">
  <div style="display:inline-block;float:left;">
  <a style="float:left;" href="{% url 'jobdetails:job_details_view_html' file=file.path_gcs crawler=crawler_id_date.id date=date %}" class="custom">
    <span class="center-block text-center fa fa-file fa-2x bluetext"></span> </a>
  </div>
  <div style="display:inline-block;">
  <h5 class="text-left blacktext" style="display:inline-block;">
    <a href="{% url 'jobdetails:job_details_view_html' file=file.path_gcs crawler=crawler_id_date.id date=date %}" class="custom">
      {{file.job_title}}</a></h5>
  <h6 class="text-left blacktext"><b><span class="redtext">Create On:</span> </b> {{file.created_at}} </h6>
  <h6 class="text-left blacktext"><b><span class="redtext">Page URL:</span></b>
    <a href="{{file.job_page_url}}" target="_blank" class="black">
    {{file.job_page_url}} </a></h6>
  <h6 class="text-left blacktext"><b><span class="redtext">GCS Path:</span></b>
    <a href="{% url 'jobdetails:job_details_view_json' file=file.path_gcs crawler=crawler_id_date.id date=date %}" class="black">
      {{file.path_gcs}}</a></h6>
  <h6 class="text-left blacktext"><b><span class="redtext">Extracted Data:</span></b>
    <a href="{% url 'jobdetails:job_details_view_data' job=file.id crawler=crawler_id_date.id date=date %}" class="black">
    View Data</a></h6>
  </div>
  </div>
  {% endfor %}
  {% endblock content %}

jobdetails/templates/jobdetails/files_table.html
{% extends 'jobdetails/base.html' %}
{% block content %}
<div class="boxlg col-lg-12 center-block text-center">
  <table>
    <tr>
      <th><span class="redtext fa fa-file fa-1x"></span></th>
      <th><span class="redtext">Name</span></th>
      <th><span class="redtext">Created On</span></th>
      <th><span class="redtext">Page Link</span></th>
      <th><span class="redtext">GCS JSON</span></th>
      <th><span class="redtext">Extracted Data</span></th>
    </tr>
    {% for file in files %}
    <tr>
      <td>  <a style="float:left;" href="{% url 'jobdetails:job_details_view_html' file=file.path_gcs crawler=crawler_id_date.id date=date %}" class="custom">
    <span class="center-block text-center fa fa-file fa-1x bluetext"></span> </a>
</td>
      <td>  <h6 class="text-left blacktext" style="display:inline-block;">
    <a href="{% url 'jobdetails:job_details_view_html' file=file.path_gcs crawler=crawler_id_date.id date=date %}" class="custom">
      {{file.job_title}}</a></h6>
</td>
<td><h6> {{file.created_at}}</h6> </td>
<td> <h6><a href="{{file.job_page_url}}" target="_blank" class="custom">
      Open</a></h6></td>
<td> <h6><a href="{% url 'jobdetails:job_details_view_json' file=file.path_gcs crawler=crawler_id_date.id date=date %}" class="custom">
      View</a></h6></td>
<td><h6> <a href="{% url 'jobdetails:job_details_view_data' job=file.id crawler=crawler_id_date.id date=date %}" class="custom">
      View</a></h6></td>
    </tr>
    {% endfor %}
  </table>
  </div>
  {% endblock content %}

jobdetails/templates/jobdetails/view_data.html
{% extends 'jobdetails/base.html' %}
{% block content %}
<script>

</script>
<div class="col-lg-12 nopadding" style="margin-left:10px;margin-right:30px;">
  <p class="wordwrap"><span class="redtext q">Title:</span> {{job_data.title}}</p>
   <p class="wordwrap"><span class="redtext q">Location:</span> {{job_data.location}}</p>
    <p class="wordwrap"><span class="redtext q">Nature:</span> {{job_data.nature}}</p>
     <p class="wordwrap"><span class="redtext q">Desc:</span> {{job_data.desc}}</p>
</div>
  {% endblock content %}

jobdetails/templates/jobdetails/view_html.html
{% extends 'jobdetails/base.html' %}
{% block content %}
<script>

</script>
<div class="col-lg-12 nopadding">
  <iframe id="html_frame" srcdoc="{{html}}" />
</div>
  {% endblock content %}

jobdetails/templates/jobdetails/view_json.html
{% extends 'jobdetails/base.html' %}
{% block content %}
<script>

</script>
<div class="col-lg-12 nopadding">
  <p class="wordwrap">{{blob_string}}</p>
</div>
  {% endblock content %}