jobdata/crawler/urls.py
from django.conf.urls import url
from crawler.views import crawler_agent_post, crawler_agent_check, job_details_agents, job_details_dates, job_details_files, job_details_view_html, job_details_view_json

urlpatterns = [
    url(r'^$', job_details_agents, name='job_details_agents'),
    url(r'^(?P<crawler>[0-9]+)/dates/$', job_details_dates, name='job_details_dates'),
    url(r'^(?P<crawler>[0-9]+)/date/(?P<date>[-\w]+)/files/$', job_details_files, name='job_details_files'),
    url(r'^(?P<crawler>[0-9]+)/date/(?P<date>[-\w]+)/(?P<file>.*)/view_html/$', job_details_view_html, name='job_details_view_html'),
    url(r'^(?P<crawler>[0-9]+)/date/(?P<date>[-\w]+)/(?P<file>.*)/view_json/$', job_details_view_json, name='job_details_view_json'),
    url(r'^crawler_agent_post/$', crawler_agent_post, name='crawler_agent_post'),
    url(r'^crawler_agent_check/$', crawler_agent_check, name='crawler_agent_check'),
]

jobdata/jobdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('crawler.urls', namespace='crawler')),
]

jobdata/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('jobdetails.urls', namespace='jobdetails')),
    url('', include('crawler_api.urls', namespace='crawler_api')),
]

jobdata/crawler/models.py
from __future__ import unicode_literals

from django.db import models


class CrawlerAgent(models.Model):
    tld = models.CharField(max_length=100)
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.tld

    def __unicode__(self):
        return u"%s" % self.id


class JobInfo(models.Model):
    crawler_agent = models.ForeignKey(CrawlerAgent)
    job_page_url = models.CharField(max_length=500)
    job_title = models.CharField(max_length=200)
    path_gcs = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return u"%s" % self.crawler_agent_id

jobdata/crawler/templates/crawler/agents.html
{% extends 'crawler/base.html' %}
{% block content %}
<script>
window.onload = function() {
var canvas = document.getElementById('myChart');
canvas.width  = 400;
canvas.height = 400;

var ctx = document.getElementById("myChart");
var data = {
  labels: [{% for crawler in crawlers%}
            "{{crawler.tld}}",
            {% endfor %}
  ],
    datasets: [
        {
            label: "Jobs Per Agent",
            backgroundColor: "rgba(255,99,132,0.2)",
            borderColor: "rgba(255,99,132,1)",
            borderWidth: 1,
            hoverBackgroundColor: "rgba(255,99,132,0.4)",
            hoverBorderColor: "rgba(255,99,132,1)",
            data: [{% for crawler in crawlers%}
                    {{crawler.votes}},
                    {% endfor %}
            ],
        }
    ]
};
var myBarChart = new Chart(ctx, {
    type: "bar",
    data: data,
    options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
                xAxes: [{
                        stacked: true
                }],
                yAxes: [{
                        stacked: true
                }]
            }
        }
});
}
</script>
<div class="col-lg-12 nopadding" style="margin-bottom:20px;">
  <canvas id="myChart" class="chardiv"></canvas>
</div>
      {% for crawler in crawlers %}
<div class="col-lg-3 center-block text-center">
  <a href="{% url 'crawler:job_details_dates' crawler=crawler.id %}" class="custom"> <span class="center-block text-center fa fa-folder fa-3x bluetext"></span></a><br/>
  <h4 class="text-center blacktext"><a href="{% url 'crawler:job_details_dates' crawler=crawler.id %}" class="custom">{{crawler.tld}}</a></h4>
  </div>
  {% endfor %}

{% endblock content %}

jobdata/crawler/templates/crawler/base.html
{% load staticfiles %}
<html>
<head>
  <title>Jobdata Details</title>
  <link rel="stylesheet" type="text/css" href="{% static 'crawler/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'crawler/style.css' %}" type="text/css">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <script src="{% static 'crawler/jquery.min.js' %}"></script>
  <script src="{% static 'crawler/bootstrap.min.js' %}"></script>
  <script src="{% static 'crawler/Chart.js'%}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container-fluid">
    <div class="row nopadding">
    <div class="col-lg-12 nopadding">
      <div class="bluebg col-lg-12 nopadding" style="margin-bottom:20px;">
      <h3 class="text-center whitetext">Job Details</h3>
      </div>
      <div class="col-lg-12 nopadding center-block text-left" style="margin-bottom:20px;">
<ol class="breadcrumb" style="margin-bottom: 5px;">
  <li><a href="{% url 'crawler:job_details_agents' %}">Home</a></li>
  {% if crawler_id %}
  <li class="active">{{crawler_id}}</li>
  {% endif %}
  {% if crawler_id_date %}
  <li><a href="{% url 'crawler:job_details_dates' crawler=crawler_id_date %}">{{crawler_id_date}}</a></li>
  <li class="active">{{date}}</li>
  {% endif %}
  {% if crawler_id_date_file %}
  <li><a href="{% url 'crawler:job_details_dates' crawler=crawler_id_date_file %}">{{crawler_id_date_file}}</a></li>
  <li><a href="{% url 'crawler:job_details_files' crawler=crawler_id_date_file date=date %}">{{date}}</a></li>
  <li class="active">{{title}}</li>
  {% endif %}
</ol>
      </div>
      <div class="col-lg-12 nopadding">
      {%block content %}

      {% endblock content %}
      </div>
          </div>
    </div>
  </div>
</body>
</html>

jobdata/crawler/templates/crawler/files.html
{% extends 'crawler/base.html' %}
{% block content %}
{% for file in files %}
<div class="boxlg col-lg-4 center-block text-center">
  <div style="display:inline-block;float:left;">
  <a style="float:left;" href="{% url 'crawler:job_details_view_html' file=file.path_gcs crawler=crawler_id_date date=date %}" class="custom">
    <span class="center-block text-center fa fa-file fa-2x bluetext"></span> </a>
  </div>
  <div style="display:inline-block;">
  <h5 class="text-left blacktext" style="display:inline-block;">
    <a href="{% url 'crawler:job_details_view_html' file=file.path_gcs crawler=crawler_id_date date=date %}" class="custom">
      {{file.job_title}}</a></h5>
  <h6 class="text-left blacktext"><b><span class="redtext">Create On:</span> </b> {{file.created_at}} </h6>
 
  <h6 class="text-left blacktext"><b><span class="redtext">Page URL:</span></b>
    <a href="{{file.job_page_url}}" target="_blank" class="black">
    {{file.job_page_url}} </a></h6>
  <h6 class="text-left blacktext"><b><span class="redtext">GCS Path:</span></b>
    <a href="{% url 'crawler:job_details_view_json' file=file.path_gcs crawler=crawler_id_date date=date %}" class="black">
      {{file.path_gcs}}</a></h6>
  </div>
  </div>
  {% endfor %}
  {% endblock content %}

jobdata/crawler/templates/crawler/view_html.html
{% extends 'crawler/base.html' %}
{% block content %}
<script>

</script>
<div class="col-lg-12 nopadding">
  <iframe id="html_frame" srcdoc="{{html}}" />
</div>
  {% endblock content %}

jobdata/crawler/templates/crawler/view_json.html
{% extends 'crawler/base.html' %}
{% block content %}
<script>

</script>
<div class="col-lg-12 nopadding">
  <p class="wordwrap">{{blob_string}}</p>
</div>
  {% endblock content %}